### PR TITLE
added different hosts and binary uploads

### PR DESCRIPTION
**Pull request by clatko**
Adding Ads API specific info according to the thread here:

https://twittercommunity.com/t/setting-up-twurl/35390

### CODE REVIEW

**Comment by clatko** [comment]
This PR only touches the README so should not have affected the build.

**Comment by andypiper** [comment]
lgtm but I'm not sure why it affected the Travis build

**Comment by clatko** [comment]
should i resubmit this?

**Comment by andypiper** [comment]
Manually added to #133

**Pull request closed without merging**
