### PR TITLE
[bug fix] Stop manual URI parsing/escaping and use CGI::parse

### PR DESCRIPTION
**Pull request by smaeda-ks**
## Problem

Sometimes, users need to pass URL strings that contain query strings as a parameter.
E.g., `website_url` parameter from the [POST accounts/:account_id/cards/website](https://developer.twitter.com/en/docs/ads/creatives/api-reference/website#post-accounts-account-id-cards-website) endpoint (Ads API).

In this case, they have to escape the URL strings in order to let the parser to parse parameters correctly:

raw: `https://developer.twitter.com/params?aaa=bbb&ccc=ddd`
parsed: `https%3A%2F%2Fdeveloper.twitter.com%2Fparams%3Faaa%3Dbbb%26ccc%3Dddd`

```
$ twurl -XPOST -H ads-api.twitter.com '/6/accounts/18ce54t1ol3/cards/website?media_key=3_1102477685765206016&name=WebsiteCardTest-buggy&website_title=WebsiteCardTest-buggy&website_url=https%3A%2F%2Fdeveloper.twitter.com%2Fparams%3Faaa%3Dbbb%26ccc%3Dddd' | jq
```

but the problem is, this code block is doing some extra job and hence the parsed parameter I included in the above twurl request gets "double-escaped".
https://github.com/twitter/twurl/blob/v0.9.3/lib/twurl/cli.rb#L161-L167

so the above twurl request will actually fail like this:
```sh
$ twurl -XPOST -H ads-api.twitter.com '/6/accounts/18ce54t1ol3/cards/website?media_key=3_1102477685765206016&name=WebsiteCardTest-buggy&website_title=WebsiteCardTest-buggy&website_url=https%3A%2F%2Fdeveloper.twitter.com%2Fparams%3Faaa%3Dbbb%26ccc%3Dddd' | jq
{
  "errors": [
    {
      "code": "INVALID_PARAMETER",
      "message": "Invalid URL encoded params",
      "parameter": "website_url"
    }
  ],
  "request": {
    "params": {
      "name": "WebsiteCardTest-buggy",
      "account_id": "18ce54t1ol3",
      "media_key": "3_1102477685765206016",
      "website_title": "WebsiteCardTest-buggy",
      "website_url": "https%3A%2F%2Fdeveloper.twitter.com%2Fparams%3Faaa%3Dbbb%26ccc%3Dddd"
    }
  }
}
```

## Solution

Just stop doing manual URI parsing and use the `CGI::parse` method instead.

Result

```sh
$ twurl -XPOST -H ads-api.twitter.com '/6/accounts/18ce54t1ol3/cards/website?media_key=3_1102477685765206016&name=WebsiteCardTest-buggy&website_title=WebsiteCardTest-buggy&website_url=https%3A%2F%2Fdeveloper.twitter.com%2Fparams%3Faaa%3Dbbb%26ccc%3Dddd' | jq
{
  "data": {
    "name": "WebsiteCardTest-buggy",
    "website_shortened_url": "https://t.co/Vji3Zyh076",
    "image_display_height": "800",
    "media_url": "https://pbs.twimg.com/media/D0zJnTDUcAA0snp.png",
    "website_display_url": "developer.twitter.com",
    "id": "84w31",
    "website_dest_url": "https://developer.twitter.com/params",
    "media_key": "3_1102477685765206016",
    "created_at": "2019-10-01T02:20:03Z",
    "image_display_width": "800",
    "website_title": "WebsiteCardTest-buggy",
    "card_uri": "card://1178857075960471554",
    "website_url": "https://developer.twitter.com/params?aaa=bbb&ccc=ddd",
    "updated_at": "2019-10-01T02:20:03Z",
    "deleted": false,
    "card_type": "WEBSITE"
  },
  "request": {
    "params": {
      "name": "WebsiteCardTest-buggy",
      "website_shortened_url": "https://t.co/Vji3Zyh076",
      "image_display_height": "800",
      "media_url": "https://pbs.twimg.com/media/D0zJnTDUcAA0snp.png",
      "website_display_url": "developer.twitter.com",
      "account_id": "18ce54t1ol3",
      "website_dest_url": "https://developer.twitter.com/params",
      "media_key": "3_1102477685765206016",
      "image_display_width": "800",
      "website_title": "WebsiteCardTest-buggy",
      "website_url": "https://developer.twitter.com/params?aaa=bbb&ccc=ddd",
      "card_type": "WEBSITE"
    }
  }
}
```

As you can see, with this patch, 
`"website_url": "https://developer.twitter.com/params?aaa=bbb&ccc=ddd",`
which is what I expect to see.

### Other bug fixes
This PR includes other bug fixes that will resolve the below issues:
https://github.com/twitter/twurl/issues/117
https://github.com/twitter/twurl/issues/77 (initial PR was: https://github.com/twitter/twurl/pull/108)

### CODE REVIEW

**Comment by andypiper** [comment]
Hey @smaeda-ks thank you! i'll connect with you and @dlamacchia as I'm not sure what the best approach is to getting this merged. Appreciate it!

**Comment by smaeda-ks** [comment]
@andypiper @dlamacchia 
Based on the test results, I'm fine with merging this to the master branch and see if other outstanding PRs can pass the test afterward. (I'm not talking about a version release here, but just maintaining the upstream branch. Releasing a new version would be a separate discussion, I guess.)

**Comment by smaeda-ks** [comment]
ping @dlamacchia

**Comment by smaeda-ks** [comment]
Just found some problems with this PR, will add more commits so please hold on. Thanks

**Comment by smaeda-ks** [comment]
@dlamacchia OK, so I fixed a bug in the latest commit: https://github.com/twitter/twurl/pull/119/commits/5c05a683729131cc1b4361ac8ffa215c6b8c3399 and now I think it's finally safe to merge.

cc: @osowskit since you originally gave me an idea of this fix.

**Comment by smaeda-ks** [comment]
@dlamacchia @andypiper 

I updated the description but now this PR includes two more major bug fixes:
https://github.com/twitter/twurl/issues/77
https://github.com/twitter/twurl/issues/117

There are also parsing/escaping issues. I'm really eager to merge this fix.

**Review by andypiper — APPROVED** [review]

**Pull request merged**
