### PR TITLE
Fix PIN authorization

### PR DESCRIPTION
**Pull request by raethlo**
### Problem
Links to this issue https://github.com/twitter/twurl/issues/95.

`twurl athorize` fails when it attempts to gets to perform pin authorization like so:
```bash
/Users/profile/.rvm/gems/ruby-2.3.2/gems/twurl-0.9.3/lib/twurl/oauth_client.rb:138:in `gets': No such file or directory @ rb_sysopen - cvKmdC4vvK98ZXsrBKXYwWYqs2tG5xybebJGct4P76Wix (Errno::ENOENT)
	from /Users/profile/.rvm/gems/ruby-2.3.2/gems/twurl-0.9.3/lib/twurl/oauth_client.rb:138:in `gets'
from /Users/profile/.rvm/gems/ruby-2.3.2/gems/twurl-0.9.3/lib/twurl/oauth_client.rb:138:in `perform_pin_authorize_workflow'
	from /Users/profile/.rvm/gems/ruby-2.3.2/gems/twurl-0.9.3/lib/twurl/oauth_client.rb:125:in `rescue in exchange_credentials_for_access_token'
from /Users/profile/.rvm/gems/ruby-2.3.2/gems/twurl-0.9.3/lib/twurl/oauth_client.rb:122:in `exchange_credentials_for_access_token'
	from /Users/profile/.rvm/gems/ruby-2.3.2/gems/twurl-0.9.3/lib/twurl/authorization_controller.rb:6:in `dispatch'
from /Users/profile/.rvm/gems/ruby-2.3.2/gems/twurl-0.9.3/lib/twurl/abstract_command_controller.rb:7:in `dispatch'
	from /Users/profile/.rvm/gems/ruby-2.3.2/gems/twurl-0.9.3/lib/twurl/cli.rb:38:in `dispatch'
from /Users/profile/.rvm/gems/ruby-2.3.2/gems/twurl-0.9.3/lib/twurl/cli.rb:21:in `run'
	from /Users/profile/.rvm/gems/ruby-2.3.2/gems/twurl-0.9.3/bin/twurl:4:in `<top (required)>'
from /Users/profile/.rvm/gems/ruby-2.3.2/bin/twurl:22:in `load'
	from /Users/profile/.rvm/gems/ruby-2.3.2/bin/twurl:22:in `<main>'
from /Users/profile/.rvm/gems/ruby-2.3.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/profile/.rvm/gems/ruby-2.3.2/bin/ruby_executable_hooks:15:in `<main>'
```

After some poking around and googling there was  an incorrect usage of `gets` in the function that handled the PIN prompt. There is also another similar, but correctly handled prompt in the codebase here:
https://github.com/raethlo/twurl/blob/7eb9a1364cbc9e8ee30a81cf36db384eb363e0af/lib/twurl/cli.rb#L128

### Solution

Using `STDIN.gets()` instead of [`Kernel.gets()`](https://ruby-doc.org/core-2.6/Kernel.html#method-i-gets) fixes the issue. 

Extra:
Needed to fix `rake build` to work because README.md was incorrectly referenced in gemspec.

### Result

The PIN auth prompt will work as expected. And as a side-product `rake build` was fixed as well.

### CODE REVIEW

**Comment by raethlo** [comment]
@smaeda-ks @andypiper what's the status here? I see you have referenced the issue in #113 as being the resolution a while ago but it is still not approved nor reviewed. The link to Travis no longer works (I vaguely recall there were some failed tests on some versions of ruby I didn't have time to look into back when I pushed this PR) so I can't see what the current CI status is. If there are still requirements  to be completed before we can merge is it in maintainers capacity to finish them? It'd be great if we could close this. Thanks

**Comment by smaeda-ks** [comment]
@raethlo Thanks for the follow-up on this. I just submitted another PR that includes CI setting changes and seems it's working well, so I'm hoping to get this merged sometime soon.

https://github.com/twitter/twurl/pull/119

**Comment by raethlo** [comment]
@smaeda-ks neat, I'll watch the PR then and rebase when it gets merged so we can merge this one as well.

**Comment by smaeda-ks** [comment]
@raethlo I've merged https://github.com/twitter/twurl/pull/119 so this should passed the test once you have updated your branch. Could you please merge master into your branch? Thanks

**Comment by smaeda-ks** [comment]
@raethlo Just pushed a commit to your folk repo and confirmed it passed the tests. Merging this PR into master. Thanks again!

**Pull request merged**
